apiVersion: v1
kind: Service
metadata:
  name: conversion-service
  labels:
    name: conversion-service
    app: currency-conversion-app
spec:
  type: NodePort
  ports:
   - port: 8100
     targetPort: 8100
     nodePort: 30005
  selector:
    name: currency-conversion-pod
    app: currency-conversion-app
