apiVersion: v1
kind: Service
metadata:
  name: exchange-service
  labels:
    name: exchange-service
    app: currency-conversion-app
spec:
  type: nodePort
  ports:
   - port: 8000
     targetPort: 8000
     nodePort: 30004
  selector:
    name: currency-exchange-pod
    app: currency-conversion-app