apiVersion: v1
kind: Pod
metadata:
  name: currency-exchange-pod
  labels:
    name: currency-exchange-pod
    app: currency-conversion-app
spec:
  containers:
  - name: currency-exchange-pod
    image: bgrapati/currency-exchange-service:latest
    ports:
     - containerPort: 8000
  